onlyBuiltDependencies:
  - '@swc/core'
  - core-js
  - esbuild
  - puppeteer
  - sharp
  - unrs-resolver

# Required by @kitschpatrol/shared-config
publicHoistPattern:
  - '@kitschpatrol/repo-config'
  - '@kitschpatrol/typescript-config'
  - 'case-police'
  - '*cspell*'
  - '*eslint*'
  - '*knip*'
  - '*mdat*'
  - '*prettier*'
  - '*remark*'
  - '*stylelint*'
