publicHoistPattern:
  - '@kitschpatrol/repo-config'
  - '@kitschpatrol/typescript-config'
  - 'case-police'
  - '*cspell*'
  - '*eslint*'
  - '*knip*'
  - '*mdat*'
  - '*prettier*'
  - '*remark*'
  - '*stylelint*'
allowBuilds:
  '@swc/core': true
  core-js: true
  esbuild: true
  puppeteer: true
  sharp: true
  unrs-resolver: true
